# TARGETS
# target: prerequisites
#	commands

# The commands are a series of steps typiclly to make the target.
# Is need to strat each line targets with tab.
#The prerequisites are file name separeted by spaces.
# these files need to exist before de commandsfor de target are run.

build:
	g++ main.cpp -o main


execute:
	./main

# clean is often used as a target that removes the outputs of other targets.
clean:
	rm -f *.o
	rm -f main